# Generated by Django 2.1.4 on 2018-12-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savetext', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteForm',
            new_name='Note',
        ),
        migrations.AlterModelTable(
            name='note',
            table='noteinfo',
        ),
    ]
