# Generated by Django 2.1.4 on 2019-01-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savetext', '0002_auto_20181222_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='mod',
        ),
        migrations.AlterModelTable(
            name='note',
            table=None,
        ),
    ]
